name: fitlyf
description: A modern glassmorphism fitness tracking app prototype.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^5.0.0
  provider: ^6.0.5
  fl_chart: ^1.1.0

